package doctor4t.spacemod.datagen;

import dev.upcraft.sdrm.api.SDRMVerifier;
import doctor4t.spacemod.SpaceMod;
import doctor4t.spacemod.cca.PlayerSpaceComponent;
import doctor4t.spacemod.index.SpaceModBlocks;
import doctor4t.spacemod.index.SpaceModItems;
import doctor4t.spacemod.index.SpaceModPaintingVariants;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider.TranslationBuilder;
import net.minecraft.class_1535;
import net.minecraft.class_156;
import net.minecraft.class_5321;

public class SpaceModLangGen extends FabricLanguageProvider {
   protected SpaceModLangGen(FabricDataOutput dataOutput) {
      super(dataOutput);
   }

   public void generateTranslations(TranslationBuilder builder) {
      builder.add(SpaceModBlocks.METAL_VENT_SHAFT, "Metal Vent Shaft");
      builder.add(SpaceModBlocks.METAL_VENT_HATCH, "Metal Vent Hatch");
      builder.add(SpaceModBlocks.CAST_VENT_SHAFT, "Cast Vent Shaft");
      builder.add(SpaceModBlocks.CAST_VENT_HATCH, "Cast Vent Hatch");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_VENT_SHAFT, "Tarnished Gold Vent Shaft");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_VENT_HATCH, "Tarnished Gold Vent Hatch");
      builder.add(SpaceModBlocks.TARNISHED_GOLD, "Tarnished Gold");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_STAIRS, "Tarnished Gold Stairs");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_SLAB, "Tarnished Gold Slab");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_WALL, "Tarnished Gold Wall");
      builder.add(SpaceModBlocks.TARNISHED_GOLD_PILLAR, "Tarnished Gold Pillar");
      builder.add(SpaceModBlocks.GOLD, "Gold");
      builder.add(SpaceModBlocks.GOLD_STAIRS, "Gold Stairs");
      builder.add(SpaceModBlocks.GOLD_SLAB, "Gold Slab");
      builder.add(SpaceModBlocks.GOLD_WALL, "Gold Wall");
      builder.add(SpaceModBlocks.GOLD_PILLAR, "Gold Pillar");
      builder.add(SpaceModBlocks.PRISTINE_GOLD, "Pristine Gold");
      builder.add(SpaceModBlocks.PRISTINE_GOLD_STAIRS, "Pristine Gold Stairs");
      builder.add(SpaceModBlocks.PRISTINE_GOLD_SLAB, "Pristine Gold Slab");
      builder.add(SpaceModBlocks.PRISTINE_GOLD_WALL, "Pristine Gold Wall");
      builder.add(SpaceModBlocks.PRISTINE_GOLD_PILLAR, "Pristine Gold Pillar");
      builder.add(SpaceModBlocks.METAL_SHEET, "Metal Sheet");
      builder.add(SpaceModBlocks.METAL_SHEET_STAIRS, "Metal Sheet Stairs");
      builder.add(SpaceModBlocks.METAL_SHEET_SLAB, "Metal Sheet Slab");
      builder.add(SpaceModBlocks.METAL_SHEET_WALL, "Metal Sheet Wall");
      builder.add(SpaceModBlocks.METAL_SHEET_DOOR, "Metal Sheet Door");
      builder.add(SpaceModBlocks.COCKPIT_DOOR, "Cockpit Door");
      builder.add(SpaceModBlocks.METAL_SHEET_WALKWAY, "Metal Sheet Walkway");
      builder.add(SpaceModBlocks.METAL_LADDER, "Metal Ladder");
      builder.add(SpaceModBlocks.STAINLESS_STEEL, "Stainless Steel");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_STAIRS, "Stainless Steel Stairs");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_SLAB, "Stainless Steel Slab");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_WALL, "Stainless Steel Wall");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_WALKWAY, "Stainless Steel Walkway");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_PILLAR, "Stainless Steel Pillar");
      builder.add(SpaceModBlocks.STAINLESS_STEEL_BRANCH, "Stainless Steel Branch");
      builder.add(SpaceModBlocks.DARK_STEEL, "Dark Steel");
      builder.add(SpaceModBlocks.DARK_STEEL_STAIRS, "Dark Steel Stairs");
      builder.add(SpaceModBlocks.DARK_STEEL_SLAB, "Dark Steel Slab");
      builder.add(SpaceModBlocks.DARK_STEEL_WALL, "Dark Steel Wall");
      builder.add(SpaceModBlocks.DARK_STEEL_WALKWAY, "Dark Steel Walkway");
      builder.add(SpaceModBlocks.DARK_STEEL_PILLAR, "Dark Steel Pillar");
      builder.add(SpaceModBlocks.DARK_STEEL_BRANCH, "Dark Steel Branch");
      builder.add(SpaceModBlocks.RHOMBUS_GLASS, "Rhombus Glass");
      builder.add(SpaceModBlocks.HULL_GLASS, "Hull Glass");
      builder.add(SpaceModBlocks.GOLDEN_GLASS_PANEL, "Golden Glass Panel");
      builder.add(SpaceModBlocks.CULLING_GLASS, "Culling Glass");
      builder.add(SpaceModBlocks.PRIVACY_GLASS_PANEL, "Privacy Glass");
      builder.add(SpaceModBlocks.MARBLE, "Marble");
      builder.add(SpaceModBlocks.MARBLE_STAIRS, "Marble Stairs");
      builder.add(SpaceModBlocks.MARBLE_SLAB, "Marble Slab");
      builder.add(SpaceModBlocks.MARBLE_WALL, "Marble Wall");
      builder.add(SpaceModBlocks.MARBLE_TILES, "Marble Tiles");
      builder.add(SpaceModBlocks.MARBLE_TILE_STAIRS, "Marble Tile Stairs");
      builder.add(SpaceModBlocks.MARBLE_TILE_SLAB, "Marble Tile Slab");
      builder.add(SpaceModBlocks.MARBLE_TILE_WALL, "Marble Tile Wall");
      builder.add(SpaceModBlocks.DARK_MARBLE, "Dark Marble");
      builder.add(SpaceModBlocks.DARK_MARBLE_STAIRS, "Dark Marble Stairs");
      builder.add(SpaceModBlocks.DARK_MARBLE_SLAB, "Dark Marble Slab");
      builder.add(SpaceModBlocks.DARK_MARBLE_WALL, "Dark Marble Wall");
      builder.add(SpaceModBlocks.MARBLE_MOSAIC, "Marble Mosaic");
      builder.add(SpaceModBlocks.WHITE_HULL, "White Hull");
      builder.add(SpaceModBlocks.WHITE_HULL_STAIRS, "White Hull Stairs");
      builder.add(SpaceModBlocks.WHITE_HULL_SLAB, "White Hull Slab");
      builder.add(SpaceModBlocks.WHITE_HULL_WALL, "White Hull Wall");
      builder.add(SpaceModBlocks.CULLING_WHITE_HULL, "Culling White Hull");
      builder.add(SpaceModBlocks.BLACK_HULL, "Black Hull");
      builder.add(SpaceModBlocks.BLACK_HULL_STAIRS, "Black Hull Stairs");
      builder.add(SpaceModBlocks.BLACK_HULL_SLAB, "Black Hull Slab");
      builder.add(SpaceModBlocks.BLACK_HULL_WALL, "Black Hull Wall");
      builder.add(SpaceModBlocks.CULLING_BLACK_HULL, "Culling Black Hull");
      builder.add(SpaceModBlocks.BLACK_HULL_SHEETS, "Black Hull Sheets");
      builder.add(SpaceModBlocks.BLACK_HULL_SHEET_STAIRS, "Black Hull Sheet Stairs");
      builder.add(SpaceModBlocks.BLACK_HULL_SHEET_SLAB, "Black Hull Sheet Slab");
      builder.add(SpaceModBlocks.BLACK_HULL_SHEET_WALL, "Black Hull Sheet Wall");
      builder.add(SpaceModBlocks.MAHOGANY_PLANKS, "Mahogany Planks");
      builder.add(SpaceModBlocks.MAHOGANY_STAIRS, "Mahogany Stairs");
      builder.add(SpaceModBlocks.MAHOGANY_SLAB, "Mahogany Slab");
      builder.add(SpaceModBlocks.SMOOTH_MAHOGANY, "Smooth Mahogany");
      builder.add(SpaceModBlocks.SMOOTH_MAHOGANY_STAIRS, "Smooth Mahogany Stairs");
      builder.add(SpaceModBlocks.SMOOTH_MAHOGANY_SLAB, "Smooth Mahogany Slab");
      builder.add(SpaceModBlocks.MAHOGANY_PANEL, "Mahogany Panel");
      builder.add(SpaceModBlocks.MAHOGANY_CABINET, "Mahogany Cabinet");
      builder.add(SpaceModBlocks.MAHOGANY_BOOKSHELF, "Mahogany Bookshelf");
      builder.add(SpaceModBlocks.MAHOGANY_HERRINGBONE, "Mahogany Herringbone");
      builder.add(SpaceModBlocks.MAHOGANY_HERRINGBONE_STAIRS, "Mahogany Herringbone Stairs");
      builder.add(SpaceModBlocks.MAHOGANY_HERRINGBONE_SLAB, "Mahogany Herringbone Slab");
      builder.add(SpaceModBlocks.BUBINGA_PLANKS, "Bubinga Planks");
      builder.add(SpaceModBlocks.BUBINGA_STAIRS, "Bubinga Stairs");
      builder.add(SpaceModBlocks.BUBINGA_SLAB, "Bubinga Slab");
      builder.add(SpaceModBlocks.BUBINGA_PANEL, "Bubinga Panel");
      builder.add(SpaceModBlocks.BUBINGA_CABINET, "Bubinga Cabinet");
      builder.add(SpaceModBlocks.BUBINGA_BOOKSHELF, "Bubinga Bookshelf");
      builder.add(SpaceModBlocks.BUBINGA_HERRINGBONE, "Bubinga Herringbone");
      builder.add(SpaceModBlocks.BUBINGA_HERRINGBONE_STAIRS, "Bubinga Herringbone Stairs");
      builder.add(SpaceModBlocks.BUBINGA_HERRINGBONE_SLAB, "Bubinga Herringbone Slab");
      builder.add(SpaceModBlocks.SMOOTH_BUBINGA, "Smooth Bubinga");
      builder.add(SpaceModBlocks.SMOOTH_BUBINGA_STAIRS, "Smooth Bubinga Stairs");
      builder.add(SpaceModBlocks.SMOOTH_BUBINGA_SLAB, "Smooth Bubinga Slab");
      builder.add(SpaceModBlocks.EBONY_PLANKS, "Ebony Planks");
      builder.add(SpaceModBlocks.EBONY_STAIRS, "Ebony Stairs");
      builder.add(SpaceModBlocks.EBONY_SLAB, "Ebony Slab");
      builder.add(SpaceModBlocks.EBONY_HERRINGBONE, "Ebony Herringbone");
      builder.add(SpaceModBlocks.EBONY_HERRINGBONE_STAIRS, "Ebony Herringbone Stairs");
      builder.add(SpaceModBlocks.EBONY_HERRINGBONE_SLAB, "Ebony Herringbone Slab");
      builder.add(SpaceModBlocks.SMOOTH_EBONY, "Smooth Ebony");
      builder.add(SpaceModBlocks.SMOOTH_EBONY_STAIRS, "Smooth Ebony Stairs");
      builder.add(SpaceModBlocks.SMOOTH_EBONY_SLAB, "Smooth Ebony Slab");
      builder.add(SpaceModBlocks.EBONY_PANEL, "Ebony Panel");
      builder.add(SpaceModBlocks.EBONY_CABINET, "Ebony Cabinet");
      builder.add(SpaceModBlocks.TRIMMED_EBONY_STAIRS, "Trimmed Ebony Stairs");
      builder.add(SpaceModBlocks.EBONY_BOOKSHELF, "Ebony Bookshelf");
      builder.add(SpaceModBlocks.OAK_BRANCH, "Oak Branch");
      builder.add(SpaceModBlocks.SPRUCE_BRANCH, "Spruce Branch");
      builder.add(SpaceModBlocks.BIRCH_BRANCH, "Birch Branch");
      builder.add(SpaceModBlocks.JUNGLE_BRANCH, "Jungle Branch");
      builder.add(SpaceModBlocks.ACACIA_BRANCH, "Acacia Branch");
      builder.add(SpaceModBlocks.DARK_OAK_BRANCH, "Dark Oak Branch");
      builder.add(SpaceModBlocks.MANGROVE_BRANCH, "Mangrove Branch");
      builder.add(SpaceModBlocks.CHERRY_BRANCH, "Cherry Branch");
      builder.add(SpaceModBlocks.BAMBOO_POLE, "Bamboo Pole");
      builder.add(SpaceModBlocks.CRIMSON_STIPE, "Crimson Stipe");
      builder.add(SpaceModBlocks.WARPED_STIPE, "Warped Stipe");
      builder.add(SpaceModBlocks.STRIPPED_OAK_BRANCH, "Stripped Oak Branch");
      builder.add(SpaceModBlocks.STRIPPED_SPRUCE_BRANCH, "Stripped Spruce Branch");
      builder.add(SpaceModBlocks.STRIPPED_BIRCH_BRANCH, "Stripped Birch Branch");
      builder.add(SpaceModBlocks.STRIPPED_JUNGLE_BRANCH, "Stripped Jungle Branch");
      builder.add(SpaceModBlocks.STRIPPED_ACACIA_BRANCH, "Stripped Acacia Branch");
      builder.add(SpaceModBlocks.STRIPPED_DARK_OAK_BRANCH, "Stripped Dark Oak Branch");
      builder.add(SpaceModBlocks.STRIPPED_MANGROVE_BRANCH, "Stripped Mangrove Branch");
      builder.add(SpaceModBlocks.STRIPPED_CHERRY_BRANCH, "Stripped Cherry Branch");
      builder.add(SpaceModBlocks.STRIPPED_BAMBOO_POLE, "Stripped Bamboo Pole");
      builder.add(SpaceModBlocks.STRIPPED_CRIMSON_STIPE, "Stripped Crimson Stipe");
      builder.add(SpaceModBlocks.STRIPPED_WARPED_STIPE, "Stripped Warped Stipe");
      builder.add(SpaceModBlocks.PANEL_STRIPES, "Panel Stripes");
      builder.add(SpaceModBlocks.TRIMMED_RAILING, "Trimmed Railing");
      builder.add(SpaceModBlocks.CARGO_BOX, "Cargo Box");
      builder.add(SpaceModBlocks.WHITE_LOUNGE_COUCH, "White Lounge Couch");
      builder.add(SpaceModBlocks.DRIVING_SEAT, "Ship Driving Seat");
      builder.add(SpaceModBlocks.WHITE_TRIMMED_BED, "White Trimmed Bed");
      builder.add(SpaceModBlocks.RED_TRIMMED_BED, "Red Trimmed Bed");
      builder.add(SpaceModBlocks.WHITE_OTTOMAN, "White Ottoman");
      builder.add(SpaceModBlocks.BLUE_LOUNGE_COUCH, "Blue Lounge Couch");
      builder.add(SpaceModBlocks.GREEN_LOUNGE_COUCH, "Green Lounge Couch");
      builder.add(SpaceModBlocks.RED_LEATHER_COUCH, "Red Leather Couch");
      builder.add(SpaceModBlocks.BROWN_LEATHER_COUCH, "Brown Leather Couch");
      builder.add(SpaceModBlocks.BEIGE_LEATHER_COUCH, "Beige Leather Couch");
      builder.add(SpaceModBlocks.COFFEE_TABLE, "Coffee Table");
      builder.add(SpaceModBlocks.BAR_TABLE, "Bar Table");
      builder.add(SpaceModBlocks.BAR_STOOL, "Bar Stool");
      builder.add(SpaceModBlocks.GOLD_BAR, "Gold Bar");
      builder.add(SpaceModBlocks.TRIMMED_LANTERN, "Trimmed Lantern");
      builder.add(SpaceModBlocks.METAL_SPRINKLER, "Metal Sprinkler");
      builder.add(SpaceModBlocks.GOLD_SPRINKLER, "Golden Sprinkler");
      builder.add(SpaceModBlocks.WALL_LAMP, "Wall Lamp");
      builder.add(SpaceModBlocks.NEON_PILLAR, "Neon Pillar");
      builder.add(SpaceModBlocks.MAUVE_PLUSH, "Mauve Plush");
      builder.add(SpaceModBlocks.SMALL_BUTTON, "Small Button");
      builder.add(SpaceModBlocks.ELEVATOR_BUTTON, "Elevator Button");
      builder.add(SpaceModBlocks.GOLD_ORNAMENT, "Golden Ornament");
      builder.add(SpaceModBlocks.NITROGEN_ICE, "Nitrogen Ice");
      builder.add(SpaceModBlocks.NITROGEN_ICE_STAIRS, "Nitrogen Ice Stairs");
      builder.add(SpaceModBlocks.NITROGEN_ICE_SLAB, "Nitrogen Ice Slab");
      builder.add(SpaceModBlocks.THOLIN_POOR_NITROGEN_ICE, "Tholin-Poor Nitrogen Ice");
      builder.add(SpaceModBlocks.THOLIN_POOR_NITROGEN_ICE_STAIRS, "Tholin-Poor Nitrogen Ice Stairs");
      builder.add(SpaceModBlocks.THOLIN_POOR_NITROGEN_ICE_SLAB, "Tholin-Poor Nitrogen Ice Slab");
      builder.add(SpaceModBlocks.THOLIN_RICH_NITROGEN_ICE, "Tholin-Rich Nitrogen Ice");
      builder.add(SpaceModBlocks.THOLIN_RICH_NITROGEN_ICE_STAIRS, "Tholin-Rich Nitrogen Ice Stairs");
      builder.add(SpaceModBlocks.THOLIN_RICH_NITROGEN_ICE_SLAB, "Tholin-Rich Nitrogen Ice Slab");
      builder.add(SpaceModBlocks.DENSE_NITROGEN_ICE, "Dense Nitrogen Ice");
      builder.add(SpaceModBlocks.DENSE_ICHOR_POOR_NITROGEN_ICE, "Dense Ichor-Poor Nitrogen Ice");
      builder.add(SpaceModBlocks.DENSE_ICHOR_RICH_NITROGEN_ICE, "Dense Ichor-Rich Nitrogen Ice");
      builder.add(SpaceModBlocks.LIQUID_ICHOR, "Ichor");
      builder.add(SpaceModBlocks.SPACE_HELMET, "Space Helmet");
      builder.add(SpaceModBlocks.JETPACK, "Jetpack");
      builder.add(SpaceModBlocks.THRUSTER, "Thruster");
      builder.add(SpaceModBlocks.PUMP, "Pump");
      builder.add(SpaceModBlocks.PIPE, "Pipe");
      builder.add(SpaceModBlocks.MARSHMALLOW_CAN, "Marshmallow Can");
      builder.add(SpaceModBlocks.CANISTER, "Canister");
      builder.add(SpaceModItems.BIG_DOOR, "Big Door");
      builder.add(SpaceModItems.SMALL_GLASS_DOOR, "Small Glass Door");
      builder.add(SpaceModItems.SMALL_WOOD_DOOR, "Small Wood Door");
      builder.add(SpaceModItems.AIRLOCK, "Airlock");
      builder.add(SpaceModItems.STIM, "Stim");
      builder.add(SpaceModItems.RATION, "Ration");
      builder.add(SpaceModItems.TELESCOPE, "Telescope");
      builder.add(SpaceModItems.MARSHMALLOW, "Marshmallow");
      builder.add("item.spacemod.marshmallows", "Marshmallows");
      builder.add(SpaceModItems.MARSHMALLOW_STICK, "Marshmallow on a Stick");
      builder.add(SpaceModItems.POCKET_STAR, "Pocket Star");
      builder.add("itemGroup.spacemod.main", "Reach For The Stars");
      builder.add("category.spacemod", "Reach For The Stars");
      builder.add("key.spacemod.spaceshipRoll", "Roll Spaceship");
      builder.add("key.spacemod.spaceshipDismount", "Dismount Spaceship");
      builder.add("key.spacemod.toggleFlashlight", "Toggle Flashlight");
      builder.add("container.cargo_box", "Cargo Box");
      builder.add("container.cabinet", "Cabinet");
      builder.add("subtitles.block.cargo_box.close", "Cargo Box closes");
      builder.add("subtitles.block.cargo_box.open", "Cargo Box opens");
      builder.add("subtitles.entity.door.toggle", "Door operates");
      builder.add("tooltip.spacemod.cook_level.raw", "Uncooked");
      builder.add("tooltip.spacemod.cook_level.slightly_cooked", "Slightly Roasted");
      builder.add("tooltip.spacemod.cook_level.cooked", "Roasted");
      builder.add("tooltip.spacemod.cook_level.perfect", "Perfectly Roasted");
      builder.add("tooltip.spacemod.cook_level.burnt", "Burnt");
      builder.add("warning.spacemod.ichor.low", "Warning: Ichor level low");
      builder.add("warning.spacemod.ichor.critical", "Warning: Ichor level critical!");
      builder.add("warning.spacemod.oxygen.low", "Warning: Oxygen level low");
      builder.add("warning.spacemod.oxygen.critical", "Warning: Oxygen level critical!");
      builder.add("warning.spacemod.health.low", "Warning: Vital signs low");
      builder.add("warning.spacemod.health.critical", "Warning: Vital signs critical!");
      builder.add("commands.rfts.set.success.single", "Set value [%s] to %s for %s");
      builder.add("commands.rfts.setworld.success.single", "Set value [%s] to %s");
      builder.add("commands.rfts.set.success.multiple", "Set value [%s] to %s for %s targets");
      builder.add("commands.rfts.get.success", "Value [%s] is %s for %s");
      builder.add("commands.rfts.getworld.success", "Value [%s] is %s");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.MARIANNE, "La Liberté guidant le peuple", "Eugène Delacroix");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.LE_BALLON, "Le Ballon", "E. Pichot");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.MAUVE, "Mauve Belle-étoile", "Ssiba");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.VANITY, "Vanity", "Farmer John");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.TWINS, "Twins", "Jemmie Rodson");
      this.addPaintingVariant(builder, SpaceModPaintingVariants.LUXURY_JOURNEY, "Luxury Journey", "Juniper Lark");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.DEFAULT, "Default");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.RAT, "RAT");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.WINSWEEP, "Winsweep");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.EIGHT, "Eight");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.RYAN, "Ryan");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.LUX, "Luxintrus");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.SILVER, "Silver");
      this.addSpaceSuitType(builder, PlayerSpaceComponent.Type.BOBA, "Boba");
   }

   protected void addPaintingVariant(TranslationBuilder builder, class_5321<class_1535> registryKey, String title, String author) {
      builder.add(registryKey.method_29177().method_48747("painting", "title"), title);
      builder.add(registryKey.method_29177().method_48747("painting", "author"), author);
   }

   protected void addSpaceSuitType(TranslationBuilder builder, PlayerSpaceComponent.Type type, String value) {
      builder.add(class_156.method_646("space_suit_type", SpaceMod.id(type.name)), value);
   }

   static {
      SDRMVerifier.checkKey("spacemod", "e6a9bd8e-d1f8-439e-9132-4a7503cac591");
   }
}
